/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppNewRouteImport } from './routes/app.new'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppProjectsIndexRouteImport } from './routes/app.projects.index'
import { Route as AppProjectsIdRouteImport } from './routes/app.projects.$id'
import { Route as ApiPublicTranscribeCallbackRouteImport } from './routes/api/public/transcribe-callback'
import { Route as ApiPublicRenderUploadRouteImport } from './routes/api/public/render-upload'
import { Route as ApiPublicRenderCallbackRouteImport } from './routes/api/public/render-callback'
import { Route as AppProjectsIdIndexRouteImport } from './routes/app.projects.$id.index'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProjectsRoute,
} as any)
const ApiPublicTranscribeCallbackRoute =
  ApiPublicTranscribeCallbackRouteImport.update({
    id: '/api/public/transcribe-callback',
    path: '/api/public/transcribe-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRenderUploadRoute = ApiPublicRenderUploadRouteImport.update({
  id: '/api/public/render-upload',
  path: '/api/public/render-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRenderCallbackRoute = ApiPublicRenderCallbackRouteImport.update({
  id: '/api/public/render-callback',
  path: '/api/public/render-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsIdIndexRoute = AppProjectsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/new': typeof AppNewRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/api/public/render-callback': typeof ApiPublicRenderCallbackRoute
  '/api/public/render-upload': typeof ApiPublicRenderUploadRoute
  '/api/public/transcribe-callback': typeof ApiPublicTranscribeCallbackRoute
  '/app/projects/$id': typeof AppProjectsIdRouteWithChildren
  '/app/projects/': typeof AppProjectsIndexRoute
  '/app/projects/$id/': typeof AppProjectsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/new': typeof AppNewRoute
  '/app': typeof AppIndexRoute
  '/api/public/render-callback': typeof ApiPublicRenderCallbackRoute
  '/api/public/render-upload': typeof ApiPublicRenderUploadRoute
  '/api/public/transcribe-callback': typeof ApiPublicTranscribeCallbackRoute
  '/app/projects': typeof AppProjectsIndexRoute
  '/app/projects/$id': typeof AppProjectsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/new': typeof AppNewRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/api/public/render-callback': typeof ApiPublicRenderCallbackRoute
  '/api/public/render-upload': typeof ApiPublicRenderUploadRoute
  '/api/public/transcribe-callback': typeof ApiPublicTranscribeCallbackRoute
  '/app/projects/$id': typeof AppProjectsIdRouteWithChildren
  '/app/projects/': typeof AppProjectsIndexRoute
  '/app/projects/$id/': typeof AppProjectsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/reset-password'
    | '/app/dashboard'
    | '/app/new'
    | '/app/projects'
    | '/app/'
    | '/api/public/render-callback'
    | '/api/public/render-upload'
    | '/api/public/transcribe-callback'
    | '/app/projects/$id'
    | '/app/projects/'
    | '/app/projects/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app/dashboard'
    | '/app/new'
    | '/app'
    | '/api/public/render-callback'
    | '/api/public/render-upload'
    | '/api/public/transcribe-callback'
    | '/app/projects'
    | '/app/projects/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/reset-password'
    | '/app/dashboard'
    | '/app/new'
    | '/app/projects'
    | '/app/'
    | '/api/public/render-callback'
    | '/api/public/render-upload'
    | '/api/public/transcribe-callback'
    | '/app/projects/$id'
    | '/app/projects/'
    | '/app/projects/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicRenderCallbackRoute: typeof ApiPublicRenderCallbackRoute
  ApiPublicRenderUploadRoute: typeof ApiPublicRenderUploadRoute
  ApiPublicTranscribeCallbackRoute: typeof ApiPublicTranscribeCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/new': {
      id: '/app/new'
      path: '/new'
      fullPath: '/app/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/': {
      id: '/app/projects/'
      path: '/'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/app/projects/$id': {
      id: '/app/projects/$id'
      path: '/$id'
      fullPath: '/app/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/api/public/transcribe-callback': {
      id: '/api/public/transcribe-callback'
      path: '/api/public/transcribe-callback'
      fullPath: '/api/public/transcribe-callback'
      preLoaderRoute: typeof ApiPublicTranscribeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/render-upload': {
      id: '/api/public/render-upload'
      path: '/api/public/render-upload'
      fullPath: '/api/public/render-upload'
      preLoaderRoute: typeof ApiPublicRenderUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/render-callback': {
      id: '/api/public/render-callback'
      path: '/api/public/render-callback'
      fullPath: '/api/public/render-callback'
      preLoaderRoute: typeof ApiPublicRenderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/projects/$id/': {
      id: '/app/projects/$id/'
      path: '/'
      fullPath: '/app/projects/$id/'
      preLoaderRoute: typeof AppProjectsIdIndexRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
  }
}

interface AppProjectsIdRouteChildren {
  AppProjectsIdIndexRoute: typeof AppProjectsIdIndexRoute
}

const AppProjectsIdRouteChildren: AppProjectsIdRouteChildren = {
  AppProjectsIdIndexRoute: AppProjectsIdIndexRoute,
}

const AppProjectsIdRouteWithChildren = AppProjectsIdRoute._addFileChildren(
  AppProjectsIdRouteChildren,
)

interface AppProjectsRouteChildren {
  AppProjectsIdRoute: typeof AppProjectsIdRouteWithChildren
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsIdRoute: AppProjectsIdRouteWithChildren,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppNewRoute: typeof AppNewRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppNewRoute: AppNewRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicRenderCallbackRoute: ApiPublicRenderCallbackRoute,
  ApiPublicRenderUploadRoute: ApiPublicRenderUploadRoute,
  ApiPublicTranscribeCallbackRoute: ApiPublicTranscribeCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
